INSERT INTO industry VALUES
    (1, 'Aerospace/ Defense'),
    (2, 'Gold'),
    (3, 'Banks'),
    (4, 'Capital Markets'),
    (5, 'Biotechnology'),
    (6, 'Computer Hardware'),
    (7, 'ETF’s'),
    (8, 'Lumber'),
    (9, 'Travel Services'),
    (10, 'Semi Conductors');
	
INSERT INTO industry_types VALUES
	('Aerospace/ Defense','AXON'),
	('Aerospace/ Defense','BA'),
	('Aerospace/ Defense','GD'),
	('Gold','NEM'),
	('Gold','FNV'),
	('Gold','GOLD'),
	('Banks','BAC'),
	('Banks','JPM'),
	('Banks','BMO'),
	('Capital Markets','GS'),
	('Capital Markets','MS'),
	('Capital Markets','SCHW'),
	('Biotechnology','NVO'),
	('Biotechnology','REGN'),
	('Biotechnology','VRTX'),
	('Computer Hardware','ANET'),
	('Computer Hardware','DELL'),
	('Computer Hardware','HP'),
	('ETF’s','IAU'),
	('ETF’s','URE'),
	('ETF’s','ELD'),
	('Lumber','SSD'),
	('Lumber','UFPI'),
	('Lumber','WFG'),
	('Travel Services','BKNG'),
	('Travel Services','TNL'),
	('Travel Services','RCL'),
	('Semi Conductors','NVDA'),
	('Semi Conductors','TSM'),
	('Semi Conductors','AVGO');

